#!/usr/bin/env bash
#
# Build tests for STM32F103RE_creality
#

# exit on first failure
set -e

#
# Build with included configs
#
use_example_configs "Voxelab Aquila 427/Default"
# opt_set
# opt_disable
# opt_enable
# opt_add
exec_test $1 $2 "Creality 4.2.7/4.2.2 - ProUI Default" "$3"

use_example_configs "Voxelab Aquila 427/MM"
# opt_set
# opt_disable
# opt_enable
# opt_add
exec_test $1 $2 "Creality 4.2.7/4.2.2 - ProUI Manual Mesh (MM)" "$3"

use_example_configs "Voxelab Aquila 427/BLT"
# opt_set
# opt_disable
# opt_enable
# opt_add
exec_test $1 $2 "Creality 4.2.7/4.2.2 - ProUI Bilinear (BLT)" "$3"

use_example_configs "Voxelab Aquila 427/UBL"
# opt_set
# opt_disable
# opt_enable
# opt_add
exec_test $1 $2 "Creality 4.2.7/4.2.2 - ProUI Unified (UBL)" "$3"

use_example_configs "Andrew427"
# opt_set
# opt_disable
# opt_enable
# opt_add
exec_test $1 $2 "Andrew's 427 - ProUI Unified (UBL)" "$3"

# clean up
restore_configs
