/*Configuration.h Defines*/

// #define CONFIGURATION_H_VERSION 02010300
// #define STRING_CONFIG_H_AUTHOR "Miguel A. Risco-Castillo (MRiscoC)"
// #define CUSTOM_VERSION_FILE Version.h
// #define MOTHERBOARD BOARD_VOXELAB_AQUILA
// #define SERIAL_PORT 1
// #define NO_AUTO_ASSIGN_WARNING
// #define NO_MAPLE_WARNING
// #define BAUDRATE 115200
// #define BAUD_RATE_GCODE
// #define SERIAL_PORT_2 -1
// #define BAUDRATE_2 250000
// #define SERIAL_PORT_3 1
// #define BAUDRATE_3 250000
// #define RS485_SERIAL_PORT 1
// #define RS485_BUS_BUFFER_SIZE 128
// #define BLUETOOTH
// #define CUSTOM_MACHINE_NAME "Aquila"
// #define MACHINE_UUID "00000000-0000-0000-0000-000000000000"
// #define X_DRIVER_TYPE TMC2208_STANDALONE
// #define Y_DRIVER_TYPE TMC2208_STANDALONE
// #define Z_DRIVER_TYPE TMC2208_STANDALONE
// #define X2_DRIVER_TYPE A4988
// #define Y2_DRIVER_TYPE A4988
// #define Z2_DRIVER_TYPE A4988
// #define Z3_DRIVER_TYPE A4988
// #define Z4_DRIVER_TYPE A4988
// #define I_DRIVER_TYPE  A4988
// #define J_DRIVER_TYPE  A4988
// #define K_DRIVER_TYPE  A4988
// #define U_DRIVER_TYPE  A4988
// #define V_DRIVER_TYPE  A4988
// #define W_DRIVER_TYPE  A4988
// #define E0_DRIVER_TYPE TMC2208_STANDALONE
// #define E1_DRIVER_TYPE A4988
// #define E2_DRIVER_TYPE A4988
// #define E3_DRIVER_TYPE A4988
// #define E4_DRIVER_TYPE A4988
// #define E5_DRIVER_TYPE A4988
// #define E6_DRIVER_TYPE A4988
// #define E7_DRIVER_TYPE A4988
// #define AXIS4_NAME 'A'
// #define AXIS4_ROTATES
// #define AXIS5_NAME 'B'
// #define AXIS5_ROTATES
// #define AXIS6_NAME 'C'
// #define AXIS6_ROTATES
// #define AXIS7_NAME 'U'
// #define AXIS7_ROTATES
// #define AXIS8_NAME 'V'
// #define AXIS8_ROTATES
// #define AXIS9_NAME 'W'
// #define AXIS9_ROTATES
// #define EXTRUDERS 1
// #define DEFAULT_NOMINAL_FILAMENT_DIA 1.75
// #define SINGLENOZZLE
// #define SINGLENOZZLE_STANDBY_TEMP
// #define SINGLENOZZLE_STANDBY_FAN
// #define SWITCHING_EXTRUDER
// #define SWITCHING_EXTRUDER_SERVO_NR 0
// #define SWITCHING_EXTRUDER_SERVO_ANGLES { 0, 90 }
// #define SWITCHING_EXTRUDER_E23_SERVO_NR 1
// #define MECHANICAL_SWITCHING_EXTRUDER
// #define SWITCHING_NOZZLE
// #define SWITCHING_NOZZLE_SERVO_NR 0
// #define SWITCHING_NOZZLE_E1_SERVO_NR 1
// #define SWITCHING_NOZZLE_SERVO_ANGLES { 0, 90 }
// #define SWITCHING_NOZZLE_SERVO_DWELL 2500
// #define MECHANICAL_SWITCHING_NOZZLE
// #define PARKING_EXTRUDER
// #define MAGNETIC_PARKING_EXTRUDER
// #define PARKING_EXTRUDER_PARKING_X { -78, 184 }
// #define PARKING_EXTRUDER_GRAB_DISTANCE 1
// #define PARKING_EXTRUDER_SOLENOIDS_INVERT
// #define PARKING_EXTRUDER_SOLENOIDS_PINS_ACTIVE LOW
// #define PARKING_EXTRUDER_SOLENOIDS_DELAY 250
// #define MANUAL_SOLENOID_CONTROL
// #define MPE_FAST_SPEED      9000
// #define MPE_SLOW_SPEED      4500
// #define MPE_TRAVEL_DISTANCE   10
// #define MPE_COMPENSATION       0
// #define SWITCHING_TOOLHEAD
// #define MAGNETIC_SWITCHING_TOOLHEAD
// #define ELECTROMAGNETIC_SWITCHING_TOOLHEAD
// #define SWITCHING_TOOLHEAD_Y_POS          235
// #define SWITCHING_TOOLHEAD_Y_SECURITY      10
// #define SWITCHING_TOOLHEAD_Y_CLEAR         60
// #define SWITCHING_TOOLHEAD_X_POS          { 215, 0 }
// #define SWITCHING_TOOLHEAD_SERVO_NR       2
// #define SWITCHING_TOOLHEAD_SERVO_ANGLES { 0, 180 }
// #define SWITCHING_TOOLHEAD_Y_RELEASE      5
// #define SWITCHING_TOOLHEAD_X_SECURITY   { 90, 150 }
// #define PRIME_BEFORE_REMOVE
// #define SWITCHING_TOOLHEAD_PRIME_MM           20
// #define SWITCHING_TOOLHEAD_RETRACT_MM         10
// #define SWITCHING_TOOLHEAD_PRIME_FEEDRATE    300
// #define SWITCHING_TOOLHEAD_RETRACT_FEEDRATE 2400
// #define SWITCHING_TOOLHEAD_Z_HOP          2
// #define MIXING_EXTRUDER
// #define MIXING_STEPPERS 2
// #define MIXING_VIRTUAL_TOOLS 16
// #define DIRECT_MIXING_IN_G1
// #define GRADIENT_MIX
// #define MIXING_PRESETS
// #define GRADIENT_VTOOL
// #define HOTEND_OFFSET_X { 0.0, 20.00 }
// #define HOTEND_OFFSET_Y { 0.0, 5.00 }
// #define HOTEND_OFFSET_Z { 0.0, 0.00 }
// #define MMU_MODEL PRUSA_MMU2
// #define PSU_CONTROL
// #define PSU_NAME "Power Supply"
// #define MKS_PWC
// #define PS_OFF_CONFIRM
// #define PS_OFF_SOUND
// #define PSU_ACTIVE_STATE LOW
// #define PSU_DEFAULT_OFF
// #define PSU_POWERUP_DELAY      250
// #define LED_POWEROFF_TIMEOUT 10000
// #define POWER_OFF_TIMER
// #define POWER_OFF_WAIT_FOR_COOLDOWN
// #define PSU_POWERUP_GCODE  "M355 S1"
// #define PSU_POWEROFF_GCODE "M355 S0"
// #define AUTO_POWER_CONTROL
// #define AUTO_POWER_FANS
// #define AUTO_POWER_E_FANS
// #define AUTO_POWER_CONTROLLERFAN
// #define AUTO_POWER_CHAMBER_FAN
// #define AUTO_POWER_COOLER_FAN
// #define AUTO_POWER_SPINDLE_LASER
// #define POWER_TIMEOUT              30
// #define POWER_OFF_DELAY          60
// #define AUTO_POWER_E_TEMP        50
// #define AUTO_POWER_CHAMBER_TEMP  30
// #define AUTO_POWER_COOLER_TEMP   26
// #define TEMP_SENSOR_0 1
// #define TEMP_SENSOR_1 0
// #define TEMP_SENSOR_2 0
// #define TEMP_SENSOR_3 0
// #define TEMP_SENSOR_4 0
// #define TEMP_SENSOR_5 0
// #define TEMP_SENSOR_6 0
// #define TEMP_SENSOR_7 0
// #define TEMP_SENSOR_BED 1
// #define TEMP_SENSOR_PROBE 0
// #define TEMP_SENSOR_CHAMBER 0
// #define TEMP_SENSOR_COOLER 0
// #define TEMP_SENSOR_BOARD 0
// #define TEMP_SENSOR_SOC 0
// #define TEMP_SENSOR_REDUNDANT 0
// #define DUMMY_THERMISTOR_998_VALUE  25
// #define DUMMY_THERMISTOR_999_VALUE 100
// #define MAX31865_SENSOR_OHMS_0      100
// #define MAX31865_CALIBRATION_OHMS_0 430
// #define MAX31865_SENSOR_OHMS_1      100
// #define MAX31865_CALIBRATION_OHMS_1 430
// #define MAX31865_SENSOR_OHMS_2      100
// #define MAX31865_CALIBRATION_OHMS_2 430
// #define TEMP_RESIDENCY_TIME         10
// #define TEMP_WINDOW                  1
// #define TEMP_HYSTERESIS              3
// #define TEMP_BED_RESIDENCY_TIME     10
// #define TEMP_BED_WINDOW              1
// #define TEMP_BED_HYSTERESIS          3
// #define TEMP_CHAMBER_RESIDENCY_TIME 10
// #define TEMP_CHAMBER_WINDOW          1
// #define TEMP_CHAMBER_HYSTERESIS      3
// #define TEMP_SENSOR_REDUNDANT_SOURCE    E1
// #define TEMP_SENSOR_REDUNDANT_TARGET    E0
// #define TEMP_SENSOR_REDUNDANT_MAX_DIFF  10
// #define HEATER_0_MINTEMP   0
// #define HEATER_1_MINTEMP   5
// #define HEATER_2_MINTEMP   5
// #define HEATER_3_MINTEMP   5
// #define HEATER_4_MINTEMP   5
// #define HEATER_5_MINTEMP   5
// #define HEATER_6_MINTEMP   5
// #define HEATER_7_MINTEMP   5
// #define BED_MINTEMP        0
// #define CHAMBER_MINTEMP    5
// #define HEATER_0_MAXTEMP 315
// #define HEATER_1_MAXTEMP 275
// #define HEATER_2_MAXTEMP 275
// #define HEATER_3_MAXTEMP 275
// #define HEATER_4_MAXTEMP 275
// #define HEATER_5_MAXTEMP 275
// #define HEATER_6_MAXTEMP 275
// #define HEATER_7_MAXTEMP 275
// #define BED_MAXTEMP      120
// #define CHAMBER_MAXTEMP  60
// #define HOTEND_OVERSHOOT 15
// #define BED_OVERSHOOT    10
// #define COOLER_OVERSHOOT  2
// #define PIDTEMP
// #define MPCTEMP
// #define PID_MAX  255
// #define PID_K1     0.95
// #define PID_DEBUG
// #define PID_PARAMS_PER_HOTEND
// #define DEFAULT_Kp_LIST {  22.20,  22.20 }
// #define DEFAULT_Ki_LIST {   1.08,   1.08 }
// #define DEFAULT_Kd_LIST { 114.00, 114.00 }
// #define DEFAULT_Kp  13.19
// #define DEFAULT_Ki   0.77
// #define DEFAULT_Kd  56.05
// #define BANG_MAX 255
// #define MPC_AUTOTUNE
// #define MPC_EDIT_MENU
// #define MPC_AUTOTUNE_MENU
// #define MPC_MAX 255
// #define MPC_HEATER_POWER { 40.0f }
// #define MPC_INCLUDE_FAN
// #define MPC_BLOCK_HEAT_CAPACITY { 16.7f }
// #define MPC_SENSOR_RESPONSIVENESS { 0.22f }
// #define MPC_AMBIENT_XFER_COEFF { 0.068f }
// #define MPC_AMBIENT_XFER_COEFF_FAN255 { 0.097f }
// #define MPC_FAN_0_ALL_HOTENDS
// #define MPC_FAN_0_ACTIVE_HOTEND
// #define FILAMENT_HEAT_CAPACITY_PERMM { 5.6e-3f }
// #define MPC_SMOOTHING_FACTOR 0.5f
// #define MPC_MIN_AMBIENT_CHANGE 1.0f
// #define MPC_STEADYSTATE 0.5f
// #define MPC_TUNING_POS { X_CENTER, Y_CENTER, 1.0f }
// #define MPC_TUNING_END_Z 10.0f
// #define MAX_BED_POWER 255
// #define PIDTEMPBED
// #define MIN_BED_POWER 0
// #define PID_BED_DEBUG
// #define DEFAULT_bedKp 128.06
// #define DEFAULT_bedKi 24.95
// #define DEFAULT_bedKd 438.07
// #define BED_LIMIT_SWITCHING
// #define BED_ANNEALING_GCODE
// #define PIDTEMPCHAMBER
// #define CHAMBER_LIMIT_SWITCHING
// #define MAX_CHAMBER_POWER 255
// #define MIN_CHAMBER_POWER 0
// #define PID_CHAMBER_DEBUG
// #define DEFAULT_chamberKp 37.04
// #define DEFAULT_chamberKi 1.40
// #define DEFAULT_chamberKd 655.17
// #define PID_OPENLOOP
// #define SLOW_PWM_HEATERS
// #define PID_FUNCTIONAL_RANGE 10
// #define PID_EDIT_MENU
// #define PID_AUTOTUNE_MENU
// #define PREVENT_COLD_EXTRUSION
// #define EXTRUDE_MINTEMP 180
// #define PREVENT_LENGTHY_EXTRUDE
// #define EXTRUDE_MAXLENGTH 1000
// #define THERMAL_PROTECTION_HOTENDS
// #define THERMAL_PROTECTION_BED
// #define THERMAL_PROTECTION_CHAMBER
// #define THERMAL_PROTECTION_COOLER
// #define COREXY
// #define COREXZ
// #define COREYZ
// #define COREYX
// #define COREZX
// #define COREZY
// #define MARKFORGED_XY
// #define MARKFORGED_YX
// #define MARKFORGED_INVERSE
// #define BELTPRINTER
// #define POLARGRAPH
// #define POLARGRAPH_MAX_BELT_LEN  1035.0
// #define DEFAULT_SEGMENTS_PER_SECOND 5
// #define PEN_UP_DOWN_MENU
// #define DELTA
// #define DEFAULT_SEGMENTS_PER_SECOND 200
// #define DELTA_HOME_TO_SAFE_ZONE
// #define DELTA_CALIBRATION_MENU
// #define DELTA_AUTO_CALIBRATION
// #define DELTA_CALIBRATION_DEFAULT_POINTS 4
// #define PROBE_MANUALLY_STEP 0.05
// #define PRINTABLE_RADIUS       140.0
// #define DELTA_MAX_RADIUS       140.0
// #define DELTA_DIAGONAL_ROD 250.0
// #define DELTA_HEIGHT 250.00
// #define DELTA_ENDSTOP_ADJ { 0.0, 0.0, 0.0 }
// #define DELTA_RADIUS 124.0
// #define DELTA_TOWER_ANGLE_TRIM { 0.0, 0.0, 0.0 }
// #define DELTA_RADIUS_TRIM_TOWER       { 0.0, 0.0, 0.0 }
// #define DELTA_DIAGONAL_ROD_TRIM_TOWER { 0.0, 0.0, 0.0 }
// #define MORGAN_SCARA
// #define MP_SCARA
// #define DEFAULT_SEGMENTS_PER_SECOND 200
// #define SCARA_LINKAGE_1 150
// #define SCARA_LINKAGE_2 150
// #define SCARA_OFFSET_X  100
// #define SCARA_OFFSET_Y  -56
// #define DEBUG_SCARA_KINEMATICS
// #define FEEDRATE_SCALING
// #define MIDDLE_DEAD_ZONE_R   0
// #define THETA_HOMING_OFFSET  0
// #define PSI_HOMING_OFFSET    0
// #define SCARA_OFFSET_THETA1  12
// #define SCARA_OFFSET_THETA2 131
// #define AXEL_TPARA
// #define DEBUG_TPARA_KINEMATICS
// #define DEFAULT_SEGMENTS_PER_SECOND 200
// #define TPARA_LINKAGE_1 120
// #define TPARA_LINKAGE_2 120
// #define TPARA_OFFSET_X    0
// #define TPARA_OFFSET_Y    0
// #define TPARA_OFFSET_Z    0
// #define FEEDRATE_SCALING
// #define MIDDLE_DEAD_ZONE_R   0
// #define THETA_HOMING_OFFSET  0
// #define PSI_HOMING_OFFSET    0
// #define POLAR
// #define DEFAULT_SEGMENTS_PER_SECOND 180
// #define PRINTABLE_RADIUS 82.0f
// #define POLAR_FAST_RADIUS 3.0f
// #define POLAR_CENTER_OFFSET 0.0f
// #define FEEDRATE_SCALING
// #define ARTICULATED_ROBOT_ARM
// #define FOAMCUTTER_XYUV
// #define ENDSTOPPULLUPS
// #define ENDSTOPPULLUP_XMIN
// #define ENDSTOPPULLUP_YMIN
// #define ENDSTOPPULLUP_ZMIN
// #define ENDSTOPPULLUP_IMIN
// #define ENDSTOPPULLUP_JMIN
// #define ENDSTOPPULLUP_KMIN
// #define ENDSTOPPULLUP_UMIN
// #define ENDSTOPPULLUP_VMIN
// #define ENDSTOPPULLUP_WMIN
// #define ENDSTOPPULLUP_XMAX
// #define ENDSTOPPULLUP_YMAX
// #define ENDSTOPPULLUP_ZMAX
// #define ENDSTOPPULLUP_IMAX
// #define ENDSTOPPULLUP_JMAX
// #define ENDSTOPPULLUP_KMAX
// #define ENDSTOPPULLUP_UMAX
// #define ENDSTOPPULLUP_VMAX
// #define ENDSTOPPULLUP_WMAX
// #define ENDSTOPPULLUP_ZMIN_PROBE
// #define ENDSTOPPULLDOWNS
// #define ENDSTOPPULLDOWN_XMIN
// #define ENDSTOPPULLDOWN_YMIN
// #define ENDSTOPPULLDOWN_ZMIN
// #define ENDSTOPPULLDOWN_IMIN
// #define ENDSTOPPULLDOWN_JMIN
// #define ENDSTOPPULLDOWN_KMIN
// #define ENDSTOPPULLDOWN_UMIN
// #define ENDSTOPPULLDOWN_VMIN
// #define ENDSTOPPULLDOWN_WMIN
// #define ENDSTOPPULLDOWN_XMAX
// #define ENDSTOPPULLDOWN_YMAX
// #define ENDSTOPPULLDOWN_ZMAX
// #define ENDSTOPPULLDOWN_IMAX
// #define ENDSTOPPULLDOWN_JMAX
// #define ENDSTOPPULLDOWN_KMAX
// #define ENDSTOPPULLDOWN_UMAX
// #define ENDSTOPPULLDOWN_VMAX
// #define ENDSTOPPULLDOWN_WMAX
// #define ENDSTOPPULLDOWN_ZMIN_PROBE
// #define X_MIN_ENDSTOP_HIT_STATE HIGH
// #define X_MAX_ENDSTOP_HIT_STATE HIGH
// #define Y_MIN_ENDSTOP_HIT_STATE HIGH
// #define Y_MAX_ENDSTOP_HIT_STATE HIGH
// #define Z_MIN_ENDSTOP_HIT_STATE HIGH
// #define Z_MAX_ENDSTOP_HIT_STATE HIGH
// #define I_MIN_ENDSTOP_HIT_STATE HIGH
// #define I_MAX_ENDSTOP_HIT_STATE HIGH
// #define J_MIN_ENDSTOP_HIT_STATE HIGH
// #define J_MAX_ENDSTOP_HIT_STATE HIGH
// #define K_MIN_ENDSTOP_HIT_STATE HIGH
// #define K_MAX_ENDSTOP_HIT_STATE HIGH
// #define U_MIN_ENDSTOP_HIT_STATE HIGH
// #define U_MAX_ENDSTOP_HIT_STATE HIGH
// #define V_MIN_ENDSTOP_HIT_STATE HIGH
// #define V_MAX_ENDSTOP_HIT_STATE HIGH
// #define W_MIN_ENDSTOP_HIT_STATE HIGH
// #define W_MAX_ENDSTOP_HIT_STATE HIGH
// #define Z_MIN_PROBE_ENDSTOP_HIT_STATE HIGH
// #define ENDSTOP_INTERRUPTS_FEATURE
// #define ENDSTOP_NOISE_THRESHOLD 2
// #define DETECT_BROKEN_ENDSTOP
// #define DISTINCT_E_FACTORS
// #define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 400, 98 }
// #define LIMITED_MAX_STEPS_EDITING
// #define MAX_STEPS_EDIT_VALUES       { 200, 200, 2000, 2000 }
// #define DEFAULT_MAX_FEEDRATE          { 800, 800, 18, 120 }
// #define LIMITED_MAX_FR_EDITING
// #define MAX_FEEDRATE_EDIT_VALUES    { 1000, 1000, 40, 200 }
// #define DEFAULT_MAX_ACCELERATION      { 800, 800, 120, 1200 }
// #define LIMITED_MAX_ACCEL_EDITING
// #define MAX_ACCEL_EDIT_VALUES       { 6000, 6000, 300, 9000 }
// #define DEFAULT_ACCELERATION                   800
// #define DEFAULT_RETRACT_ACCELERATION           800
// #define DEFAULT_TRAVEL_ACCELERATION           1000
// #define DEFAULT_ANGULAR_ACCELERATION        3000
// #define DEFAULT_ANGULAR_TRAVEL_ACCELERATION 3000
// #define CLASSIC_JERK
// #define DEFAULT_XJERK 10.0
// #define DEFAULT_YJERK 10.0
// #define DEFAULT_ZJERK  0.4
// #define DEFAULT_IJERK  0.3
// #define DEFAULT_JJERK  0.3
// #define DEFAULT_KJERK  0.3
// #define DEFAULT_UJERK  0.3
// #define DEFAULT_VJERK  0.3
// #define DEFAULT_WJERK  0.3
// #define TRAVEL_EXTRA_XYJERK 0.0
// #define LIMITED_JERK_EDITING
// #define MAX_JERK_EDIT_VALUES { 20, 20, 1, 20 }
// #define DEFAULT_EJERK    5.0
// #define JUNCTION_DEVIATION_MM 0.013
// #define JD_HANDLE_SMALL_SEGMENTS
// #define S_CURVE_ACCELERATION
// #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
// #define USE_PROBE_FOR_Z_HOMING
// #define Z_MIN_PROBE_PIN PB1
// #define PROBE_MANUALLY
// #define FIX_MOUNTED_PROBE
// #define NOZZLE_AS_PROBE
// #define Z_PROBE_SERVO_NR 0
// #define Z_SERVO_ANGLES { 70, 0 }
// #define Z_SERVO_MEASURE_ANGLE 45
// #define Z_SERVO_INTERMEDIATE_STOW
// #define Z_SERVO_DEACTIVATE_AFTER_STOW
// #define BLTOUCH
// #define MAGLEV4
// #define MAGLEV_TRIGGER_PIN 11
// #define MAGLEV_TRIGGER_DELAY 15
// #define TOUCH_MI_PROBE
// #define TOUCH_MI_RETRACT_Z 0.5
// #define TOUCH_MI_DEPLOY_XPOS (X_MAX_BED + 2)
// #define TOUCH_MI_MANUAL_DEPLOY
// #define BD_SENSOR
// #define BD_SENSOR_PROBE_NO_STOP
// #define SOLENOID_PROBE
// #define Z_PROBE_SLED
// #define SLED_DOCKING_OFFSET 5
// #define RACK_AND_PINION_PROBE
// #define Z_PROBE_DEPLOY_X  X_MIN_POS
// #define Z_PROBE_RETRACT_X X_MAX_POS
// #define MAG_MOUNTED_PROBE
// #define PROBE_DEPLOY_FEEDRATE (133*60)
// #define PROBE_STOW_FEEDRATE   (133*60)
// #define MAG_MOUNTED_DEPLOY_1 { PROBE_DEPLOY_FEEDRATE, { 245, 114, 30 } }
// #define MAG_MOUNTED_DEPLOY_2 { PROBE_DEPLOY_FEEDRATE, { 210, 114, 30 } }
// #define MAG_MOUNTED_DEPLOY_3 { PROBE_DEPLOY_FEEDRATE, {   0,   0,  0 } }
// #define MAG_MOUNTED_DEPLOY_4 { PROBE_DEPLOY_FEEDRATE, {   0,   0,  0 } }
// #define MAG_MOUNTED_DEPLOY_5 { PROBE_DEPLOY_FEEDRATE, {   0,   0,  0 } }
// #define MAG_MOUNTED_STOW_1   { PROBE_STOW_FEEDRATE,   { 245, 114, 20 } }
// #define MAG_MOUNTED_STOW_2   { PROBE_STOW_FEEDRATE,   { 245, 114,  0 } }
// #define MAG_MOUNTED_STOW_3   { PROBE_STOW_FEEDRATE,   { 230, 114,  0 } }
// #define MAG_MOUNTED_STOW_4   { PROBE_STOW_FEEDRATE,   { 210, 114, 20 } }
// #define MAG_MOUNTED_STOW_5   { PROBE_STOW_FEEDRATE,   {   0,   0,  0 } }
// #define DUET_SMART_EFFECTOR
// #define SMART_EFFECTOR_MOD_PIN  -1
// #define SENSORLESS_PROBING
// #define Z_PROBE_ALLEN_KEY
// #define Z_PROBE_ALLEN_KEY_DEPLOY_1 { 30.0, PRINTABLE_RADIUS, 100.0 }
// #define Z_PROBE_ALLEN_KEY_DEPLOY_1_FEEDRATE XY_PROBE_FEEDRATE
// #define Z_PROBE_ALLEN_KEY_DEPLOY_2 { 0.0, PRINTABLE_RADIUS, 100.0 }
// #define Z_PROBE_ALLEN_KEY_DEPLOY_2_FEEDRATE (XY_PROBE_FEEDRATE)/10
// #define Z_PROBE_ALLEN_KEY_DEPLOY_3 { 0.0, (PRINTABLE_RADIUS) * 0.75, 100.0 }
// #define Z_PROBE_ALLEN_KEY_DEPLOY_3_FEEDRATE XY_PROBE_FEEDRATE
// #define Z_PROBE_ALLEN_KEY_STOW_1 { -64.0, 56.0, 23.0 }
// #define Z_PROBE_ALLEN_KEY_STOW_1_FEEDRATE XY_PROBE_FEEDRATE
// #define Z_PROBE_ALLEN_KEY_STOW_2 { -64.0, 56.0, 3.0 }
// #define Z_PROBE_ALLEN_KEY_STOW_2_FEEDRATE (XY_PROBE_FEEDRATE)/10
// #define Z_PROBE_ALLEN_KEY_STOW_3 { -64.0, 56.0, 50.0 }
// #define Z_PROBE_ALLEN_KEY_STOW_3_FEEDRATE XY_PROBE_FEEDRATE
// #define Z_PROBE_ALLEN_KEY_STOW_4 { 0.0, 0.0, 50.0 }
// #define Z_PROBE_ALLEN_KEY_STOW_4_FEEDRATE XY_PROBE_FEEDRATE
// #define NOZZLE_TO_PROBE_OFFSET { 10, 10, -1 }
// #define NOZZLE_TO_PROBE_OFFSET {-10,  5, -1 }
// #define NOZZLE_TO_PROBE_OFFSET {  5, -5, -1 }
// #define NOZZLE_TO_PROBE_OFFSET {-15,-10, -1 }
// #define NOZZLE_TO_PROBE_OFFSET { -45.0, -7.0, 0 }
// #define PROBING_TOOL 0
// #define PROBE_TOOLCHANGE_NO_MOVE
// #define PROBING_MARGIN 0
// #define XY_PROBE_FEEDRATE (180*60)
// #define Z_PROBE_FEEDRATE_FAST (9*60)
// #define Z_PROBE_FEEDRATE_SLOW (150)
// #define PROBE_ACTIVATION_SWITCH
// #define PROBE_ACTIVATION_SWITCH_STATE LOW
// #define PROBE_ACTIVATION_SWITCH_PIN PC6
// #define PROBE_TARE
// #define PROBE_TARE_TIME  200
// #define PROBE_TARE_DELAY 200
// #define PROBE_TARE_STATE HIGH
// #define PROBE_TARE_PIN PA5
// #define PROBE_TARE_ONLY_WHILE_INACTIVE
// #define PROBE_ENABLE_DISABLE
// #define PROBE_ENABLE_PIN -1
// #define MULTIPLE_PROBING 0
// #define EXTRA_PROBING    1
// #define Z_CLEARANCE_DEPLOY_PROBE   10
// #define Z_CLEARANCE_BETWEEN_PROBES  5
// #define Z_CLEARANCE_MULTI_PROBE     5
// #define Z_PROBE_ERROR_TOLERANCE     3
// #define Z_AFTER_PROBING           5
// #define Z_PROBE_LOW_POINT          -2
// #define PROBE_OFFSET_XMIN -50
// #define PROBE_OFFSET_XMAX  50
// #define PROBE_OFFSET_YMIN -50
// #define PROBE_OFFSET_YMAX  50
// #define PROBE_OFFSET_ZMIN -20
// #define PROBE_OFFSET_ZMAX  20
// #define Z_MIN_PROBE_REPEATABILITY_TEST
// #define PAUSE_BEFORE_DEPLOY_STOW
// #define PAUSE_PROBE_DEPLOY_WHEN_TRIGGERED
// #define PROBING_HEATERS_OFF
// #define WAIT_FOR_BED_HEATER
// #define WAIT_FOR_HOTEND
// #define PROBING_FANS_OFF
// #define PROBING_ESTEPPERS_OFF
// #define PROBING_STEPPERS_OFF
// #define DELAY_BEFORE_PROBING 200
// #define PREHEAT_BEFORE_PROBING
// #define PROBING_NOZZLE_TEMP 120
// #define PROBING_BED_TEMP     50
// #define X_ENABLE_ON 0
// #define Y_ENABLE_ON 0
// #define Z_ENABLE_ON 0
// #define E_ENABLE_ON 0
// #define I_ENABLE_ON 0
// #define J_ENABLE_ON 0
// #define K_ENABLE_ON 0
// #define U_ENABLE_ON 0
// #define V_ENABLE_ON 0
// #define W_ENABLE_ON 0
// #define DISABLE_X
// #define DISABLE_Y
// #define DISABLE_Z
// #define DISABLE_I
// #define DISABLE_J
// #define DISABLE_K
// #define DISABLE_U
// #define DISABLE_V
// #define DISABLE_W
// #define DISABLE_REDUCED_ACCURACY_WARNING
// #define DISABLE_E
// #define DISABLE_OTHER_EXTRUDERS
// #define INVERT_X_DIR false
// #define INVERT_Y_DIR false
// #define INVERT_Z_DIR true
// #define INVERT_I_DIR false
// #define INVERT_J_DIR false
// #define INVERT_K_DIR false
// #define INVERT_U_DIR false
// #define INVERT_V_DIR false
// #define INVERT_W_DIR false
// #define INVERT_E0_DIR false
// #define INVERT_E1_DIR false
// #define INVERT_E2_DIR false
// #define INVERT_E3_DIR false
// #define INVERT_E4_DIR false
// #define INVERT_E5_DIR false
// #define INVERT_E6_DIR false
// #define INVERT_E7_DIR false
// #define NO_MOTION_BEFORE_HOMING
// #define HOME_AFTER_DEACTIVATE
// #define Z_IDLE_HEIGHT Z_HOME_POS
// #define Z_CLEARANCE_FOR_HOMING   5
// #define Z_AFTER_HOMING        10
// #define XY_AFTER_HOMING { 10, 10 }
// #define EVENT_GCODE_AFTER_HOMING "M300 P440 S200"
// #define X_HOME_DIR -1
// #define Y_HOME_DIR -1
// #define Z_HOME_DIR -1
// #define I_HOME_DIR -1
// #define J_HOME_DIR -1
// #define K_HOME_DIR -1
// #define U_HOME_DIR -1
// #define V_HOME_DIR -1
// #define W_HOME_DIR -1
// #define X_SAFETY_STOP
// #define Y_SAFETY_STOP
// #define Z_SAFETY_STOP
// #define I_SAFETY_STOP
// #define J_SAFETY_STOP
// #define K_SAFETY_STOP
// #define U_SAFETY_STOP
// #define V_SAFETY_STOP
// #define W_SAFETY_STOP
// #define X_BED_SIZE 220
// #define Y_BED_SIZE 220
// #define X_MIN_POS 0
// #define Y_MIN_POS 0
// #define Z_MIN_POS 0
// #define X_MAX_POS 230
// #define Y_MAX_POS 220
// #define Z_MAX_POS 250
// #define I_MIN_POS 0
// #define I_MAX_POS 50
// #define J_MIN_POS 0
// #define J_MAX_POS 50
// #define K_MIN_POS 0
// #define K_MAX_POS 50
// #define U_MIN_POS 0
// #define U_MAX_POS 50
// #define V_MIN_POS 0
// #define V_MAX_POS 50
// #define W_MIN_POS 0
// #define W_MAX_POS 50
// #define MIN_SOFTWARE_ENDSTOPS
// #define MIN_SOFTWARE_ENDSTOP_X
// #define MIN_SOFTWARE_ENDSTOP_Y
// #define MIN_SOFTWARE_ENDSTOP_Z
// #define MIN_SOFTWARE_ENDSTOP_I
// #define MIN_SOFTWARE_ENDSTOP_J
// #define MIN_SOFTWARE_ENDSTOP_K
// #define MIN_SOFTWARE_ENDSTOP_U
// #define MIN_SOFTWARE_ENDSTOP_V
// #define MIN_SOFTWARE_ENDSTOP_W
// #define MAX_SOFTWARE_ENDSTOPS
// #define MAX_SOFTWARE_ENDSTOP_X
// #define MAX_SOFTWARE_ENDSTOP_Y
// #define MAX_SOFTWARE_ENDSTOP_Z
// #define MAX_SOFTWARE_ENDSTOP_I
// #define MAX_SOFTWARE_ENDSTOP_J
// #define MAX_SOFTWARE_ENDSTOP_K
// #define MAX_SOFTWARE_ENDSTOP_U
// #define MAX_SOFTWARE_ENDSTOP_V
// #define MAX_SOFTWARE_ENDSTOP_W
// #define SOFT_ENDSTOPS_MENU_ITEM
// #define FILAMENT_RUNOUT_SENSOR
// #define FIL_RUNOUT_ENABLED_DEFAULT false
// #define NUM_RUNOUT_SENSORS   1
// #define FIL_RUNOUT_STATE     HIGH
// #define FIL_RUNOUT_PULLUP
// #define FIL_RUNOUT_PULLDOWN
// #define WATCH_ALL_RUNOUT_SENSORS
// #define FIL_RUNOUT1_STATE LOW
// #define FIL_RUNOUT1_PULLUP
// #define FIL_RUNOUT1_PULLDOWN
// #define FIL_RUNOUT2_STATE LOW
// #define FIL_RUNOUT2_PULLUP
// #define FIL_RUNOUT2_PULLDOWN
// #define FIL_RUNOUT3_STATE LOW
// #define FIL_RUNOUT3_PULLUP
// #define FIL_RUNOUT3_PULLDOWN
// #define FIL_RUNOUT4_STATE LOW
// #define FIL_RUNOUT4_PULLUP
// #define FIL_RUNOUT4_PULLDOWN
// #define FIL_RUNOUT5_STATE LOW
// #define FIL_RUNOUT5_PULLUP
// #define FIL_RUNOUT5_PULLDOWN
// #define FIL_RUNOUT6_STATE LOW
// #define FIL_RUNOUT6_PULLUP
// #define FIL_RUNOUT6_PULLDOWN
// #define FIL_RUNOUT7_STATE LOW
// #define FIL_RUNOUT7_PULLUP
// #define FIL_RUNOUT7_PULLDOWN
// #define FIL_RUNOUT8_STATE LOW
// #define FIL_RUNOUT8_PULLUP
// #define FIL_RUNOUT8_PULLDOWN
// #define FILAMENT_RUNOUT_SCRIPT "M600"
// #define FILAMENT_RUNOUT_DISTANCE_MM 25
// #define FILAMENT_MOTION_SENSOR
// #define FILAMENT_SWITCH_AND_MOTION
// #define NUM_MOTION_SENSORS   1
// #define FIL_MOTION1_PIN    -1
// #define FIL_MOTION1_STATE LOW
// #define FIL_MOTION1_PULLUP
// #define FIL_MOTION1_PULLDOWN
// #define FIL_MOTION2_STATE LOW
// #define FIL_MOTION2_PULLUP
// #define FIL_MOTION2_PULLDOWN
// #define FIL_MOTION3_STATE LOW
// #define FIL_MOTION3_PULLUP
// #define FIL_MOTION3_PULLDOWN
// #define FIL_MOTION4_STATE LOW
// #define FIL_MOTION4_PULLUP
// #define FIL_MOTION4_PULLDOWN
// #define FIL_MOTION5_STATE LOW
// #define FIL_MOTION5_PULLUP
// #define FIL_MOTION5_PULLDOWN
// #define FIL_MOTION6_STATE LOW
// #define FIL_MOTION6_PULLUP
// #define FIL_MOTION6_PULLDOWN
// #define FIL_MOTION7_STATE LOW
// #define FIL_MOTION7_PULLUP
// #define FIL_MOTION7_PULLDOWN
// #define FIL_MOTION8_STATE LOW
// #define FIL_MOTION8_PULLUP
// #define FIL_MOTION8_PULLDOWN
// #define AUTO_BED_LEVELING_3POINT
// #define AUTO_BED_LEVELING_LINEAR
// #define AUTO_BED_LEVELING_BILINEAR
// #define AUTO_BED_LEVELING_UBL
// #define MESH_BED_LEVELING
// #define Z_PROBE_END_SCRIPT "G1 Z10 F12000\nG1 X15 Y330\nG1 Z0.5\nG1 Z10"
// #define RESTORE_LEVELING_AFTER_G28
// #define ENABLE_LEVELING_AFTER_G28
// #define PREHEAT_BEFORE_LEVELING
// #define LEVELING_NOZZLE_TEMP 175
// #define LEVELING_BED_TEMP     50
// #define DEBUG_LEVELING_FEATURE
// #define MANUAL_PROBE_START_Z 0.2
// #define ENABLE_LEVELING_FADE_HEIGHT
// #define DEFAULT_LEVELING_FADE_HEIGHT 10.0
// #define SEGMENT_LEVELED_MOVES
// #define LEVELED_SEGMENT_LENGTH 5.0
// #define G26_MESH_VALIDATION
// #define MESH_TEST_NOZZLE_SIZE    0.4
// #define MESH_TEST_LAYER_HEIGHT   0.2
// #define MESH_TEST_HOTEND_TEMP  205
// #define MESH_TEST_BED_TEMP      60
// #define G26_XY_FEEDRATE         20
// #define G26_XY_FEEDRATE_TRAVEL 100
// #define G26_RETRACT_MULTIPLIER   1.0
// #define GRID_MAX_POINTS_X 5
// #define GRID_MAX_POINTS_Y GRID_MAX_POINTS_X
// #define MESH_EDIT_MENU
// #define MESH_INSET 10
// #define PROBE_Y_FIRST
// #define EXTRAPOLATE_BEYOND_GRID
// #define ABL_BILINEAR_SUBDIVISION
// #define BILINEAR_SUBDIVISIONS 3
// #define MESH_EDIT_GFX_OVERLAY
// #define MESH_EDIT_MENU
// #define MESH_INSET 10
// #define GRID_MAX_POINTS_X 7
// #define GRID_MAX_POINTS_Y GRID_MAX_POINTS_X
// #define UBL_HILBERT_CURVE
// #define UBL_TILT_ON_MESH_POINTS
// #define UBL_TILT_ON_MESH_POINTS_3POINT
// #define UBL_MESH_EDIT_MOVES_Z
// #define UBL_SAVE_ACTIVE_ON_M500
// #define UBL_Z_RAISE_WHEN_OFF_MESH 2.5
// #define UBL_MESH_WIZARD
// #define AVOID_OBSTACLES
// #define CLIP_W  23
// #define CLIP_H  14
// #define OBSTACLE1 { (X_BED_SIZE) / 4     - (CLIP_W) / 2,                       0, (X_BED_SIZE) / 4     + (CLIP_W) / 2, CLIP_H }
// #define OBSTACLE2 { (X_BED_SIZE) * 3 / 4 - (CLIP_W) / 2,                       0, (X_BED_SIZE) * 3 / 4 + (CLIP_W) / 2, CLIP_H }
// #define OBSTACLE3 { (X_BED_SIZE) / 4     - (CLIP_W) / 2, (Y_BED_SIZE) - (CLIP_H), (X_BED_SIZE) / 4     + (CLIP_W) / 2, Y_BED_SIZE }
// #define OBSTACLE4 { (X_BED_SIZE) * 3 / 4 - (CLIP_W) / 2, (Y_BED_SIZE) - (CLIP_H), (X_BED_SIZE) * 3 / 4 + (CLIP_W) / 2, Y_BED_SIZE }
// #define G29J_MESH_TILT_MARGIN ((CLIP_H) + 1)
// #define MESH_EDIT_MENU
// #define MESH_INSET 10
// #define GRID_MAX_POINTS_X 5
// #define GRID_MAX_POINTS_Y GRID_MAX_POINTS_X
// #define MESH_G28_REST_ORIGIN
// #define LCD_BED_LEVELING
// #define MESH_EDIT_Z_STEP  0.025
// #define LCD_PROBE_Z_RANGE 4
// #define MESH_EDIT_MENU
// #define LCD_BED_TRAMMING
// #define BED_TRAMMING_HEIGHT      0.0
// #define BED_TRAMMING_Z_HOP       5.0
// #define BED_TRAMMING_INCLUDE_CENTER
// #define BED_TRAMMING_USE_PROBE
// #define BED_TRAMMING_INSET_LFRB { 35, 35, 35, 35 }
// #define BED_TRAMMING_PROBE_TOLERANCE 0.05f
// #define BED_TRAMMING_VERIFY_RAISED
// #define BED_TRAMMING_AUDIO_FEEDBACK
// #define BED_TRAMMING_INSET_LFRB { 25.4, 25.4, 25.4, 25.4 }
// #define BED_TRAMMING_LEVELING_ORDER { LF, RF, RB, LB }
// #define BED_SCREW_INSET 35
// #define BED_CENTER_AT_0_0
// #define MANUAL_X_HOME_POS 0
// #define MANUAL_Y_HOME_POS 0
// #define MANUAL_Z_HOME_POS 0
// #define MANUAL_I_HOME_POS 0
// #define MANUAL_J_HOME_POS 0
// #define MANUAL_K_HOME_POS 0
// #define MANUAL_U_HOME_POS 0
// #define MANUAL_V_HOME_POS 0
// #define MANUAL_W_HOME_POS 0
// #define Z_SAFE_HOMING
// #define Z_SAFE_HOMING_X_POINT X_CENTER
// #define Z_SAFE_HOMING_Y_POINT Y_CENTER
// #define Z_SAFE_HOMING_POINT_ABSOLUTE
// #define HOMING_FEEDRATE_MM_M { (60*60), (60*60), (8*60) }
// #define VALIDATE_HOMING_ENDSTOPS
// #define SKEW_CORRECTION
// #define XY_DIAG_AC 282.8427124746
// #define XY_DIAG_BD 282.8427124746
// #define XY_SIDE_AD 200
// #define XY_SKEW_FACTOR 0.0
// #define SKEW_CORRECTION_FOR_Z
// #define XZ_DIAG_AC 282.8427124746
// #define XZ_DIAG_BD 282.8427124746
// #define YZ_DIAG_AC 282.8427124746
// #define YZ_DIAG_BD 282.8427124746
// #define YZ_SIDE_AD 200
// #define XZ_SKEW_FACTOR 0.0
// #define YZ_SKEW_FACTOR 0.0
// #define SKEW_CORRECTION_GCODE
// #define EEPROM_SETTINGS
// #define DISABLE_M503
// #define EEPROM_CHITCHAT
// #define EEPROM_BOOT_SILENT
// #define EEPROM_AUTO_INIT
// #define EEPROM_INIT_NOW
// #define HOST_KEEPALIVE_FEATURE
// #define DEFAULT_KEEPALIVE_INTERVAL 5
// #define BUSY_WHILE_HEATING
// #define INCH_MODE_SUPPORT
// #define TEMPERATURE_UNITS_SUPPORT
// #define PREHEAT_1_LABEL       "PLA"
// #define PREHEAT_1_TEMP_HOTEND 210
// #define PREHEAT_1_TEMP_BED     60
// #define PREHEAT_1_TEMP_CHAMBER 35
// #define PREHEAT_1_FAN_SPEED     0
// #define PREHEAT_2_LABEL       "ABS"
// #define PREHEAT_2_TEMP_HOTEND 240
// #define PREHEAT_2_TEMP_BED     75
// #define PREHEAT_2_TEMP_CHAMBER 35
// #define PREHEAT_2_FAN_SPEED     0
// #define PREHEAT_3_LABEL       "Warmup"
// #define PREHEAT_3_TEMP_HOTEND 200
// #define PREHEAT_3_TEMP_BED     50
// #define PREHEAT_3_FAN_SPEED     0
// #define PREHEAT_4_LABEL       "TPU"
// #define PREHEAT_4_TEMP_HOTEND 230
// #define PREHEAT_4_TEMP_BED     80
// #define PREHEAT_4_FAN_SPEED     128
// #define PREHEAT_5_LABEL       "CUSTOM"
// #define PREHEAT_5_TEMP_HOTEND 240
// #define PREHEAT_5_TEMP_BED     60
// #define PREHEAT_5_FAN_SPEED   128
// #define NOZZLE_PARK_FEATURE
// #define NOZZLE_PARK_POINT { 0, 200, 50 }
// #define NOZZLE_PARK_MOVE          0
// #define NOZZLE_PARK_Z_RAISE_MIN  10
// #define NOZZLE_PARK_XY_FEEDRATE 125
// #define NOZZLE_PARK_Z_FEEDRATE   25
// #define NOZZLE_CLEAN_FEATURE
// #define NOZZLE_CLEAN_PATTERN_LINE
// #define NOZZLE_CLEAN_PATTERN_ZIGZAG
// #define NOZZLE_CLEAN_PATTERN_CIRCLE
// #define NOZZLE_CLEAN_DEFAULT_PATTERN 0
// #define NOZZLE_CLEAN_STROKES     4
// #define NOZZLE_CLEAN_TRIANGLES  3
// #define NOZZLE_CLEAN_START_POINT { {  30, 30, (Z_MIN_POS + 1) } }
// #define NOZZLE_CLEAN_END_POINT   { { 100, 30, (Z_MIN_POS + 1) } }
// #define NOZZLE_CLEAN_CIRCLE_RADIUS 6.5
// #define NOZZLE_CLEAN_CIRCLE_FN 10
// #define NOZZLE_CLEAN_CIRCLE_MIDDLE NOZZLE_CLEAN_START_POINT
// #define NOZZLE_CLEAN_GOBACK
// #define NOZZLE_CLEAN_NO_Z
// #define NOZZLE_CLEAN_NO_Y
// #define NOZZLE_CLEAN_MIN_TEMP 170
// #define NOZZLE_CLEAN_HEATUP
// #define WIPE_SEQUENCE_COMMANDS "G0 X2 Y200 Z50\nG0 Z0.3\nG0 Z0.3\nG92 E0\nG1 Y140 E10 F1500\nG1 X2.3 F5000\nG92 E0\nG1 Y10 E10 F1200\nG92 E0"
// #define PRINTJOB_TIMER_AUTOSTART
// #define PRINTCOUNTER
// #define PRINTCOUNTER_SAVE_INTERVAL 60
// #define PASSWORD_FEATURE
// #define PASSWORD_LENGTH 4
// #define PASSWORD_ON_STARTUP
// #define PASSWORD_UNLOCK_GCODE
// #define PASSWORD_CHANGE_GCODE
// #define PASSWORD_ON_SD_PRINT_MENU
// #define PASSWORD_AFTER_SD_PRINT_END
// #define PASSWORD_AFTER_SD_PRINT_ABORT
// #define LCD_LANGUAGE en
// #define DISPLAY_CHARSET_HD44780 JAPANESE
// #define LCD_INFO_SCREEN_STYLE 0
// #define SDSUPPORT
// #define SD_CHECK_AND_RETRY
// #define NO_LCD_MENUS
// #define SLIM_LCD_MENUS
// #define ENCODER_PULSES_PER_STEP 4
// #define ENCODER_STEPS_PER_MENU_ITEM 1
// #define REVERSE_ENCODER_DIRECTION
// #define REVERSE_MENU_DIRECTION
// #define REVERSE_SELECT_DIRECTION
// #define ENCODER_NOISE_FILTER
// #define ENCODER_SAMPLES 10
// #define INDIVIDUAL_AXIS_HOMING_MENU
// #define INDIVIDUAL_AXIS_HOMING_SUBMENU
// #define SPEAKER
// #define LCD_FEEDBACK_FREQUENCY_DURATION_MS 2
// #define LCD_FEEDBACK_FREQUENCY_HZ 5000
// #define TONE_QUEUE_LENGTH 4
// #define STARTUP_TUNE { 698, 300, 0, 50, 523, 50, 0, 25, 494, 50, 0, 25, 523, 100, 0, 50, 554, 300, 0, 100, 523, 300 }
// #define REPRAP_DISCOUNT_SMART_CONTROLLER
// #define YHCB2004
// #define RADDS_DISPLAY
// #define ULTIMAKERCONTROLLER
// #define ULTIPANEL
// #define PANEL_ONE
// #define G3D_PANEL
// #define RIGIDBOT_PANEL
// #define MAKEBOARD_MINI_2_LINE_DISPLAY_1602
// #define ZONESTAR_LCD
// #define ULTRA_LCD
// #define RA_CONTROL_PANEL
// #define LCD_SAINSMART_I2C_1602
// #define LCD_SAINSMART_I2C_2004
// #define LCM1602
// #define LCD_I2C_PANELOLU2
// #define LCD_I2C_VIKI
// #define SAV_3DLCD
// #define FF_INTERFACEBOARD
// #define TFTGLCD_PANEL_SPI
// #define TFTGLCD_PANEL_I2C
// #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
// #define K3D_FULL_GRAPHIC_SMART_CONTROLLER
// #define REPRAPWORLD_GRAPHICAL_LCD
// #define VIKI2
// #define miniVIKI
// #define WYH_L12864
// #define MINIPANEL
// #define MAKRPANEL
// #define ELB_FULL_GRAPHIC_CONTROLLER
// #define BQ_LCD_SMART_CONTROLLER
// #define CARTESIO_UI
// #define LCD_FOR_MELZI
// #define ULTI_CONTROLLER
// #define MKS_MINI_12864
// #define MKS_MINI_12864_V3
// #define MKS_LCD12864A
// #define MKS_LCD12864B
// #define FYSETC_MINI_12864_X_X
// #define FYSETC_MINI_12864_1_2
// #define FYSETC_MINI_12864_2_0
// #define FYSETC_MINI_12864_2_1
// #define FYSETC_GENERIC_12864_1_1
// #define BTT_MINI_12864
// #define ANET_FULL_GRAPHICS_LCD
// #define ANET_FULL_GRAPHICS_LCD_ALT_WIRING
// #define AZSMZ_12864
// #define SILVER_GATE_GLCD_CONTROLLER
// #define EMOTION_TECH_LCD
// #define U8GLIB_SSD1306
// #define SAV_3DGLCD
// #define U8GLIB_SSD1306
// #define U8GLIB_SH1106
// #define OLED_PANEL_TINYBOY2
// #define MKS_12864OLED
// #define MKS_12864OLED_SSD1306
// #define ZONESTAR_12864LCD
// #define ZONESTAR_12864OLED
// #define ZONESTAR_12864OLED_SSD1306
// #define U8GLIB_SH1106_EINSTART
// #define OVERLORD_OLED
// #define FYSETC_242_OLED_12864
// #define K3D_242_OLED_CONTROLLER
// #define DGUS_LCD_UI ORIGIN
// #define USE_MKS_GREEN_UI
// #define LCD_SCREEN_ROTATE 90
// #define IA_CREALITY_BOOT_DELAY 1500
// #define MALYAN_LCD
// #define TOUCH_UI_FTDI_EVE
// #define ANYCUBIC_LCD_CHIRON
// #define ANYCUBIC_LCD_I3MEGA
// #define ANYCUBIC_LCD_GCODE_EXT
// #define ANYCUBIC_LCD_VYPER
// #define NEXTION_TFT
// #define PANELDUE
// #define EXTENSIBLE_UI
// #define EXTUI_LOCAL_BEEPER
// #define MKS_TS35_V2_0
// #define MKS_ROBIN_TFT24
// #define MKS_ROBIN_TFT28
// #define MKS_ROBIN_TFT32
// #define MKS_ROBIN_TFT35
// #define MKS_ROBIN_TFT43
// #define MKS_ROBIN_TFT_V1_1R
// #define TFT_TRONXY_X5SA
// #define ANYCUBIC_TFT35
// #define LONGER_LK_TFT28
// #define ANET_ET4_TFT28
// #define ANET_ET5_TFT35
// #define BIQU_BX_TFT70
// #define BTT_TFT35_SPI_V1_0
// #define TFT_GENERIC
// #define TFT_DRIVER AUTO
// #define TFT_INTERFACE_FSMC
// #define TFT_INTERFACE_SPI
// #define TFT_RES_320x240
// #define TFT_RES_480x272
// #define TFT_RES_480x320
// #define TFT_RES_1024x600
// #define TFT_CLASSIC_UI
// #define TFT_COLOR_UI
// #define TFT_LVGL_UI
// #define TFT_FONT  NOTOSANS
// #define TFT_THEME BLACK_MARLIN
// #define TFT_SHARED_IO
// #define COMPACT_MARLIN_BOOT_LOGO
// #define MKS_WIFI_MODULE
// #define TFT_ROTATION TFT_NO_ROTATION
// #define DWIN_LCD_PROUI
// #define HAS_DACAI 1
// #define TJC_DISPLAY
// #define PROUI_EX 1
// #define HAS_TOOLBAR 1
// #define HAS_GCODE_PREVIEW 1
// #define DISABLE_TUNING_GRAPH 0
// #define HAS_ESDIAG 1
// #define HAS_CGCODE 1
// #define HAS_LOCKSCREEN 1
// #define USE_GRID_MESHVIEWER 1
// #define HAS_CUSTOM_COLORS 1
// #define ALT_COLOR_MENU 0
// #define ACTIVATE_MESH_ITEM
// #define RUNOUT_TUNE_ITEM
// #define HS_MENU_ITEM
// #define PLOT_TUNE_ITEM
// #define PLR_TUNE_ITEM
// #define JD_TUNE_ITEM
// #define ADVK_TUNE_ITEM
// #define SHOW_REAL_POS
// #define CCLOUD_PRINT_SUPPORT
// #define TRAMWIZ_MENU_ITEM
// #define MEDIASORT_MENU_ITEM
// #define ENC_MENU_ITEM
// #define SHOW_SPEED_IND
// #define NO_BLINK_IND
// #define CR10_STOCKDISPLAY
// #define RET6_12864_LCD
// #define ENDER2_STOCKDISPLAY
// #define TOUCH_SCREEN
// #define BUTTON_DELAY_EDIT      50
// #define BUTTON_DELAY_MENU     250
// #define DISABLE_ENCODER
// #define TOUCH_IDLE_SLEEP_MINS 5
// #define TOUCH_SCREEN_CALIBRATION
// #define TOUCH_CALIBRATION_X 12316
// #define TOUCH_CALIBRATION_Y -8981
// #define TOUCH_OFFSET_X        -43
// #define TOUCH_OFFSET_Y        257
// #define TOUCH_ORIENTATION TOUCH_LANDSCAPE
// #define TOUCH_CALIBRATION_AUTO_SAVE
// #define SINGLE_TOUCH_NAVIGATION
// #define REPRAPWORLD_KEYPAD
// #define REPRAPWORLD_KEYPAD_MOVE_STEP 10.0
// #define EASYTHREED_UI
// #define NUM_M106_FANS 1
// #define FAN_SOFT_PWM
// #define SOFT_PWM_SCALE 0
// #define SOFT_PWM_DITHER
// #define BARICUDA
// #define TEMP_STAT_LEDS
// #define BLINKM
// #define PCA9632
// #define PCA9533
// #define RGB_LED
// #define RGBW_LED
// #define RGB_LED_R_PIN 34
// #define RGB_LED_G_PIN 43
// #define RGB_LED_B_PIN 35
// #define RGB_LED_W_PIN -1
// #define RGB_STARTUP_TEST
// #define RGB_STARTUP_TEST_INNER_MS 10
// #define NEOPIXEL_LED
// #define NEOPIXEL_TYPE          NEO_GRBW
// #define NEOPIXEL_PIN               PA13
// #define NEOPIXEL2_TYPE  NEOPIXEL_TYPE
// #define NEOPIXEL2_PIN               5
// #define NEOPIXEL_PIXELS              30
// #define NEOPIXEL_IS_SEQUENTIAL
// #define NEOPIXEL_BRIGHTNESS         127
// #define NEOPIXEL_STARTUP_TEST
// #define NEOPIXEL2_SEPARATE
// #define NEOPIXEL2_PIXELS           15
// #define NEOPIXEL2_BRIGHTNESS      127
// #define NEOPIXEL2_STARTUP_TEST
// #define NEOPIXEL_M150_DEFAULT      -1
// #define NEOPIXEL2_INSERIES
// #define NEOPIXEL_BKGD_INDEX_FIRST   0
// #define NEOPIXEL_BKGD_INDEX_LAST    5
// #define NEOPIXEL_BKGD_COLOR         { 255, 255, 255, 0 }
// #define NEOPIXEL_BKGD_TIMEOUT_COLOR {  25,  25,  25, 0 }
// #define NEOPIXEL_BKGD_ALWAYS_ON
// #define PRINTER_EVENT_LEDS
// #define NUM_SERVOS 3
// #define SERVO_DELAY { 300 }
// #define DEACTIVATE_SERVOS_AFTER_MOVE
// #define EDITABLE_SERVO_ANGLES
// #define SERVO_DETACH_GCODE
